artifacts_root: artifacts


data_ingestion:
  root_dir        : artifacts/Stage01_Data_Ingestion
  source_URL      : https://github.com/datasign-tist/Data-Repository/raw/refs/heads/main/Wine_Quality_Data.zip
  local_data_file : artifacts/Stage01_Data_Ingestion/Data.zip
  unzip_dir       : artifacts/Stage01_Data_Ingestion

data_validation:
  root_dir       : artifacts/Stage02_Data_Validation
  unzip_data_dir : artifacts/Stage01_Data_Ingestion/winequality-red.csv
  STATUS_FILE    : artifacts/Stage02_Data_Validation/status.txt

data_transformation:
  root_dir  : artifacts/Stage03_Data_Transformation
  data_path : artifacts/Stage01_Data_Ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/Stage04_Data_Modelling
  train_data_path: artifacts/Stage03_Data_Transformation/train.csv
  test_data_path: artifacts/Stage03_Data_Transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/Stage05_Model_Evaluation
  test_data_path: artifacts/Stage03_Data_Transformation/test.csv
  model_path: artifacts/Stage04_Data_Modelling/model.joblib
  metric_file_name: artifacts/Stage05_Model_Evaluation/metrics.json